version: '3.0'


services:
  bot:
    container_name: bot
    build: 
      context: .
      dockerfile: ./docker/bot.Dockerfile
    restart: unless-stopped
    user: root
    ports:
      - 8080:8080
    env_file: 
      - ./.env
    volumes: 
      - ./bot:/app
    depends_on: 
      - actions
  
  actions:
    container_name: actions
    build: 
      context: .
      dockerfile: ./docker/actions.Dockerfile
    volumes: 
      - ./actions:/app/actions
    ports:
      - 5055:5055
  
  docs:
    container_name: docs
    build: 
      context: .
      dockerfile: ./docker/docs.Dockerfile
    volumes: 
      - ./docs:/srv/jekyll
    ports: 
      - 4000:4000